version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  POSTGRES_HOST:
  # Taiga settings
  TAIGA_SECRET_KEY:
  TAIGA_SITES_DOMAIN:
  TAIGA_SITES_SCHEME:
  TAIGA_URL: "${TAIGA_SITES_SCHEME}://${TAIGA_SITES_DOMAIN}"
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL:
  EMAIL_USE_TLS:
  EMAIL_USE_SSL:
  EMAIL_HOST:
  EMAIL_PORT:
  EMAIL_HOST_USER:
  EMAIL_HOST_PASSWORD:
  # Registration
  PUBLIC_REGISTER_ENABLED:
  # Telemetry settings
  ENABLE_TELEMETRY: "False"
  # Rabbitmq settings
  # should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER:
  RABBITMQ_PASS:
  # Github settings
  # Get these in your profile https://github.com/settings/apps
  # or in your organization profile https://github.com/organizations/{ORGANIZATION-SLUG}/settings/applications
  #GITHUB_API_CLIENT_ID: "github-api-client-id"
  #GITHUB_API_CLIENT_SECRET: "github-api-client-secret"
  # Gitlab settings
  # Get these in your profile https://{YOUR-GITLAB}/profile/applications
  # or in your organization profile https://{YOUR-GITLAB}/admin/applications
  #GITLAB_API_CLIENT_ID: "gitlab-api-client-id"
  #GITLAB_API_CLIENT_SECRET: "gitlab-api-client-secret"
  #GITLAB_URL: "gitlab-url"
  # IMPORTERS
  # ENABLE_GITHUB_IMPORTER: "False"
  # GITHUB_IMPORTER_CLIENT_ID: "client-id-from-github"
  # GITHUB_IMPORTER_CLIENT_SECRET: "client-secret-from-github"
  # ENABLE_JIRA_IMPORTER: "False"
  # JIRA_IMPORTER_CONSUMER_KEY: "consumer-key-from-jira"
  # JIRA_IMPORTER_CERT: "cert-from-jira"
  # JIRA_IMPORTER_PUB_CERT: "pub-cert-from-jira"
  # ENABLE_TRELLO_IMPORTER: "False"
  # TRELLO_IMPORTER_API_KEY: "api-key-from-trello"
  # TRELLO_IMPORTER_SECRET_KEY: "secret-key-from-trello"
  ENABLE_SLACK:
  TAIGA_MEDIA_DIR:
  TAIGA_STATIC_DIR:
  MEDIA_URL: "${TAIGA_URL}/media/"
  STATIC_URL: "${TAIGA_URL}/static/"


x-volumes:
  &default-back-volumes
  - ${TAIGA_STATIC_DIR}:/taiga-back/static
  - ${TAIGA_MEDIA_DIR}:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py:ro


services:
  # taiga-db:
  #   image: postgres:12.3
  #   environment:
  #     POSTGRES_DB:
  #     POSTGRES_USER:
  #     POSTGRES_PASSWORD:
  #   volumes:
  #     - taiga-db-data:/var/lib/postgresql/data
  #   networks:
  #     - taiga
  #   ports:
  #     - "${POSTGRES_HOST_PORT}:5432"

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      # - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq
    restart: unless-stopped

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      # - taiga-db
      - taiga-back
      - taiga-async-rabbitmq
    restart: unless-stopped

  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
      RABBITMQ_DEFAULT_VHOST:
    networks:
      - taiga
    restart: unless-stopped

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "${TAIGA_SITES_SCHEME}://${TAIGA_SITES_DOMAIN}"
      TAIGA_WEBSOCKETS_URL: "wss://${TAIGA_SITES_DOMAIN}"
      PUBLIC_REGISTER_ENABLED: "true"
      DEFAULT_LANGUAGE: "fr"
      DEBUG: "false"
      DEBUG_INFO: "false"
      # Get these in your profile https://github.com/settings/apps
      # or in your organization profile https://github.com/organizations/{ORGANIZATION-SLUG}/settings/applications
      #GITHUB_CLIENT_ID: "github-client-id"
      # Get these in your profile https://{YOUR-GITLAB}/profile/applications
      # or in your organization profile https://{YOUR-GITLAB}/admin/applications
      #GITLAB_CLIENT_ID: "gitlab-client-id"
      #GITLAB_URL: "gitlab-url"
      ENABLE_SLACK: "true"
      # IMPORTERS
      ENABLE_GITHUB_IMPORTER: "false"
      ENABLE_JIRA_IMPORTER: "false"
      ENABLE_TRELLO_IMPORTER: "false"
    networks:
      - taiga
    #volumes:
     # - ./conf.json:/usr/share/nginx/html/conf.json:ro
    restart: unless-stopped

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER:
      RABBITMQ_PASS:
      TAIGA_SECRET_KEY:
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq
    restart: unless-stopped

  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
      RABBITMQ_DEFAULT_VHOST:
    networks:
      - taiga
    restart: unless-stopped

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: 360
      SECRET_KEY: ${TAIGA_SECRET_KEY}
    networks:
      - taiga
    restart: unless-stopped

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "${APP_HOST_PORT}:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - ${TAIGA_STATIC_DIR}:/taiga/static
      - ${TAIGA_MEDIA_DIR}:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
    restart: unless-stopped

volumes:
  taiga-static-data:
  taiga-media-data:
  # taiga-db-data:

networks:
  taiga:
