version: "3.5"

x-environment:
  &default-back-environment
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  POSTGRES_HOST:
  TAIGA_SECRET_KEY:
  # these rabbitmq settings should be the same as
  # in taiga-rabbitmq and taiga-events services
  RABBITMQ_USER:
  RABBITMQ_PASS:
  CELERY_ENABLED: "False"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py:ro

services:
  taiga-manage:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
    volumes: *default-back-volumes
    networks:
      - taiga
